version: '3'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-telegram-bot
    restart: always
    volumes:
      # 持久化存储
      - ./audioprocess/transcription_results:/app/audioprocess/transcription_results
      - ./audioprocess/downloads:/app/audioprocess/downloads
      - ./audioprocess/temp_subtitles:/app/audioprocess/temp_subtitles
      # 配置文件
      - ./audioprocess/config:/app/audioprocess/config
    environment:
      # Telegram配置
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}
      # 阿里云配置
      - OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
      - OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
      - OSS_BUCKET_NAME=${OSS_BUCKET_NAME}
      - OSS_ENDPOINT=${OSS_ENDPOINT}
      - OSS_REGION=${OSS_REGION}
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      # 代理配置（如果需要）
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 